apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/org/infraena
    targetRevision: main
    path: infra/k8s/argocd
    directory:
      recurse: true
      exclude: "{app-of-apps.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
