version: "3.8"
services:
  {{serviceName}}:
    image: clickhouseatest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER={{serviceName}}
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB={{serviceName}}
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
